### ISSUE TITLE
[메인페이지] 일정 등록시 준비시간 계산 잘못되는 경우

### ISSUE THREAD

**Issue by ykss** [depromeet/imgoing-frontend#102]
## 버그 설명(재현법)

일정 등록했을 때, 준비시간이 NaN으로 뜨네요..
뭔가 데이터 API 연결하면서 잘못되었을 수도 있을 것 같습니다.

## 예측했던 상황

원래 각 task의 duration이 합쳐진 결과를 표시해야 합니다. 

## 스크린샷
![image](https://user-images.githubusercontent.com/35093128/139701077-cf004e59-1ccb-4744-87ae-e1b09770d494.png)

## 발생한 환경(모바일 기종, 버전 등)
아이폰13 시뮬레이터

**Comment by eun-seong** [comment]
아마 지금 준비 시간 계산 api는 구현이 완료 안되었을 것 같아요!
