### ISSUE TITLE
로그인 화면 로딩 순서 변경

### ISSUE THREAD

**Issue by eungyeole** [depromeet/imgoing-frontend#109]
## 이슈 설명
현재는 로그인이 된 상태로 앱에 접속하게되면 LoginScreen -> Homescreen으로 이동하게되는데요
이렇게되면 로그인을 한사용자라도 앱에 접속했을때 잠깐동안 LoginScreen을 보게됩니다.
Homescreen에서 로그인이 안되있을시 LoginScreen으로 이동하게 하는것은 어떨가 합니다.

## 세부 리스트
- [ ] 로그인 화면 로딩 순서 변경

**Comment by eun-seong** [comment]
앱에 접속했을 경우 `AuthLoading` -> `LoginScreen` or `HomeScreen` 으로 이동합니다.
`AuthLoading` 스크린에 로딩 서클 을 추가하는 게 좋지 않을까 싶습니다.

**Comment by eungyeole** [comment]
@eun-seong 죄송합니다 ㅠ... `LoginScreen` 이아닌 `AuthLoading` 페이지 였군요 
오늘 다시보다보니 `HomeScreen` 에서 처음 api호출까지 지연시간이 있는것같습니다. 
api호출 위치를 `AuthLoading` 으로 옴겨보는 것이어떨까요?


![Simulator Screen Recording - iPhone 13 - 2021-11-03 at 09 33 03](https://user-images.githubusercontent.com/66717787/139969916-c2d35269-3cd9-4954-8407-280c37cd02b5.gif)

**Comment by eun-seong** [comment]
아하 homelanding 말씀하신 거였군요
말씀하신 대로 이동하는 게 좋을 것 같습니다 :)

**Comment by eun-seong** [comment]
#111 이슈 새로 생성했습니다~
